# Generated by Django 4.1.1 on 2023-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccidentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=50)),
                ("date_time", models.DateTimeField()),
                ("cause", models.CharField(max_length=50)),
                ("number_of_vehicle", models.IntegerField(max_length=5)),
                ("people_injured", models.IntegerField(max_length=5)),
            ],
        ),
    ]
