# Generated by Django 4.1.1 on 2023-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentdetail",
            name="number_of_vehicle",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="accidentdetail",
            name="people_injured",
            field=models.IntegerField(),
        ),
    ]
